### PR TITLE
Fix some memory leaks for msvc builds.

### PR DESCRIPTION
**Pull request by Rossmaxx**
This is the first fix for runtime issues for LADSPA plugins on MSVC.

This pr (and subsequent fixes) should be merged before https://github.com/LMMS/lmms/pull/6758

### CODE REVIEW

**Review by messmerd — APPROVED** [review]

**Comment by JohannesLorenz** [comment]
The issue occurs 2 more times in the same file. This will cause the same issue. I would recommend adding another PR for those?

**Comment by Rossmaxx** [comment]
> The issue occurs 2 more times in the same file. This will cause the same issue. I would recommend adding another PR for those?

Where exactly?

**Comment by JohannesLorenz** [comment]
> Where exactly?

Of course, the other 2 `STACKALLOC`s

**Comment by Rossmaxx** [comment]
> Of course, the other 2 STACKALLOCs

No need of any changes there. All I did here is move the limiter's `STACKALLOC` out of the loop, the other two are not enclosed in any loops so no issues there.

**Comment by JohannesLorenz** [comment]
Line 396 is not the beginning of a loop?

**Pull request merged**
