### PR TITLE
Fix overloaded virtual methods for gcc >= 13

### PR DESCRIPTION
**Pull request by FyiurAmron**
Required for GCC >= 13. More details: https://github.com/LMMS/lmms/issues/7284

Mirrors the upstream change at https://github.com/calf-studio-gear/calf/blob/master/src/calf/analyzer.h#L61 , which is part of https://github.com/calf-studio-gear/calf/commit/a64edc8603e99f6cd8de11bbac5b8922541a4aa3 , done ca. 2019 :)

### CODE REVIEW

**Comment by FyiurAmron** [comment]
@messmerd or whomever has the write access here: review & merge would be very welcome :D

**Review by messmerd — APPROVED** [review]

**Comment by tresf** [comment]
Hmm... First, thanks!

However, if upstream has already patched this behavior, we would normally prefer a rebase to address things like this to avoid even more conflicts.  @JohannesLorenz has been maintaining this fork, so I'll assign him for review.

**Comment by FyiurAmron** [comment]
@tresf yeah, the changes in question are not that far after the last split - if I'm not mistaken, it's just 6 months after the last common commit (back from 2019) and in total 20, mostly cosmetic, commits up vs `calf-studio-gear/calf` - and I agree that a rebase would be a much better option than copy-pasting. Anyway, I'm leaving this PR open for the time being as as a reference point.

**Comment by JohannesLorenz** [comment]
Thanks @FyiurAmron for the PR.

> we would normally prefer a rebase to address things like this to avoid even more conflicts

Agreeing to @tresf . It would be nice if you could open a new PR which does the "rebase".

**Comment by FyiurAmron** [comment]
superseded by https://github.com/LMMS/veal/pull/13

**Pull request closed without merging**
